### ISSUE TITLE
As a developer I need access to Information Architecture for the application

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#13]
# Feature/ Fix 
Neither for this we need to build out the information architecture for the application which includes

- [x] A list of application features 
- [x] Data Models for the application elements 
- [x] User stories for application use 

# Acceptance test 
We should have user stories for the application that enable us to let a user go through the application end to end

**Comment by zacck** [comment]
Well we have User stories, features and most of the required models for this
