### ISSUE TITLE
As a user I want to create a user account on the system so I can use the Application

### ISSUE THREAD

**Issue by zacck** [LittleKidogo/MoneyLog#29]
When a user is joining the system they need to be able to create an account so that they can use the parts of the system that need one to have a user account which is everything since every MoneyLog is scoped to one or more users.

# Todos 
Enable user to sign in using fed auth]
- [x] enable sign in with Google
- [x] enable sign in with Twitter
- [x] enable sign in with Facebook

## Acceptance Criteria
A user should be able to create an account by signing into the system using facebook, twitter and google accounts

**Comment by zacck** [comment]
Seeing as all the auth platforms are onboard I want to consider this one closed
